CREATE TABLE IF NOT EXISTS Urls
(
  id INTEGER PRIMARY KEY,
  alias TEXT NOT NULL UNIQUE,
  url TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_alias ON Urls(alias);
