// Code generated by mockery v2.53.2. DO NOT EDIT.

package redirect

import mock "github.com/stretchr/testify/mock"

// MockURLGetter is an autogenerated mock type for the URLGetter type
type MockURLGetter struct {
	mock.Mock
}

type MockURLGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLGetter) EXPECT() *MockURLGetter_Expecter {
	return &MockURLGetter_Expecter{mock: &_m.Mock}
}

// GetURL provides a mock function with given fields: alias
func (_m *MockURLGetter) GetURL(alias string) (string, error) {
	ret := _m.Called(alias)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(alias)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(alias)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(alias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLGetter_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockURLGetter_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - alias string
func (_e *MockURLGetter_Expecter) GetURL(alias interface{}) *MockURLGetter_GetURL_Call {
	return &MockURLGetter_GetURL_Call{Call: _e.mock.On("GetURL", alias)}
}

func (_c *MockURLGetter_GetURL_Call) Run(run func(alias string)) *MockURLGetter_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockURLGetter_GetURL_Call) Return(_a0 string, _a1 error) *MockURLGetter_GetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLGetter_GetURL_Call) RunAndReturn(run func(string) (string, error)) *MockURLGetter_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLGetter creates a new instance of MockURLGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLGetter {
	mock := &MockURLGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
